ユーザーを追加するSQL文を追加
nakamuraitsuki/maximum_forum pull request #34
Opened 2024-10-28 10:05 UTC by nomura0928

2024-10-28 10:37 UTC, batora9 requested changes
文法的な修正はこんな感じなんだけど、このままだとパスワードが平文でデータベースに挿入されちゃってよくないからハッシュ化(平たく言うと暗号)してから挿入したいね。そのへん直してほしいかな～

2024-10-28 10:37 UTC, batora9 commented on backend/main.go
> +	now := time.Now()
ユーザー追加にtimeパッケージは使わないからここはいらないかな

2024-10-28 10:37 UTC, batora9 commented on backend/main.go
> +	_, err := db.Exec(addUser, user.name, user.pw_hash)
```suggestion
	_, err := db.Exec(addUser, user.ID, user.Name, user.PwHash)
```

2024-10-28 11:25 UTC, nomura0928 commented
`func encryptPassword(password string) (string, error) {
	// パスワードの文字列をハッシュ化する
	hash, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
	if err != nil {
		return "", err
	}
	return string(hash), nil
}`
これではっ

2024-10-28 11:27 UTC, nomura0928 commented
> func encryptPassword(password string) (string, error) {
	// パスワードの文字列をハッシュ化する
	hash, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
	if err != nil {
		return "", err
	}
	return string(hash), nil
}
これでハッシュ化できますかね？

2024-10-29 01:58 UTC, nakamuraitsuki commented
> func encryptPassword(password string) (string, error) { // パスワードの文字列をハッシュ化する hash, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost) if err != nil { return "", err } return string(hash), nil } これでハッシュ化できますかね？

出来そうです。その方法では、goの提供しているbcryptというパッケージを使ってハッシュ化をしているので、それをimportのところに書くことを忘れないように気をつけましょう。
公式ドキュメントはこれ：[https://pkg.go.dev/golang.org/x/crypto/bcrypt](url)
内容についても少し調べてみると面白いかもしれません。

2024-10-29 02:17 UTC, nakamuraitsuki commented
あと、ちょっとした確認ですが、SQLってのが何か（今回書いていただいた中でどの内容に当たるか）ってわかりますか

2024-10-29 03:49 UTC, nomura0928 commented
あんまりわからないです

2024-10-29 03:59 UTC, nakamuraitsuki commented on backend/main.go
> +	addUser = "INSERT INTO users (id, name, pw_hash) VALUES (?, ?, ?, ?)"
この部分の"INSERT INTO users (id, name, pw_hash) VALUES (?, ?, ?)の部分がSQLです。
詳しくは[https://hnavi.co.jp/knowledge/blog/sql/](url)を読んでみてください
簡単に言うと、データベースに対する操作命令文のことです。
この命令文を、今回はGOという言語を用いて実行しているイメージです

2024-10-29 04:01 UTC, nakamuraitsuki requested changes

2024-10-29 04:01 UTC, nakamuraitsuki commented on backend/main.go
> +	addUser = "INSERT INTO users (id, name, pw_hash) VALUES (?, ?, ?, ?)"
VALUESのところの?が一個多いです。このVALUESの部分は入れる値を受け取るところなので、個数はid, name, pw_hashの3つになります

2024-10-29 04:33 UTC, nakamuraitsuki commented on backend/main.go
> +	addUser = "INSERT INTO users (id, name, pw_hash) VALUES (?, ?, ?, ?)"
ごめんなさい、間違えたことを言いました。
データベース設計の時点でidはAUTOINCREMENT（自動で1ずつ追加される）に設定されているので、idをこちらから渡す必要はありません。
つまり？の数は2つです

2024-10-29 05:39 UTC, nomura0928 commented on backend/main.go
> +	addUser = "INSERT INTO users (id, name, pw_hash) VALUES (?, ?, ?, ?)"
SQLのところ以外は削除したほうがいいですかね？

2024-10-29 08:50 UTC, nakamuraitsuki commented on backend/main.go
> +	addUser = "INSERT INTO users (id, name, pw_hash) VALUES (?, ?, ?, ?)"
今回はこのままで大丈夫です。

2024-10-29 08:51 UTC, nakamuraitsuki requested changes

2024-10-29 08:51 UTC, nakamuraitsuki commented on backend/main.go
> +	_, err := db.Exec(addUser, user.ID, user.Name, user.PwHash)
SQLの修正をしたら、ここも変更が必要になるはずなので、合わせてお願いします。

2024-10-29 14:53 UTC, nakamuraitsuki requested changes
よろしくお願いします

2024-10-29 14:53 UTC, nakamuraitsuki commented on backend/main.go
> +	"bcrypt"
インポートの仕方が違います

2024-10-29 14:53 UTC, nakamuraitsuki commented on backend/main.go
> +	_, err := db.Exec(addUser, user.ID, user.Name, encryptPassword(user.PwHash))
idは外部から送られてくるものではなく、goのなか、もっと言うならデータベースに入るときに処理されるものなので、ここに書く必要はありません

2024-10-29 14:55 UTC, nakamuraitsuki commented on backend/main.go
> +	"bcrypt"
`"golang.org/x/crypto/bcrypt"`

2024-10-29 15:21 UTC, nakamuraitsuki requested changes
buildしてみて気づいた点を挙げました。
修正よろしくお願いします

2024-10-29 15:21 UTC, nakamuraitsuki commented on backend/main.go
> +	"golang.org/x/crypto/bcrypt"
このままビルドしてもエラーが出るはずです。
ここに書くだけでなく、プロジェクトに導入する必要があるためです。
`go get golang.org/x/crypto/bcrypt`をターミナルで実行することでプロジェクトにbcryptを導入しましょう

2024-10-29 15:21 UTC, nakamuraitsuki commented on backend/main.go
> +func encryptPassword(password string) (string, error) {
ここでの宣言の仕方と後の呼び出し方が違うような気がします。
あと、元も子もない話ですが、わざわざ関数に入れる必要もないかと思います。この先ハッシュ化を行うのはユーザー追加の部分だけなので、複雑なコードをまとめることで再利用しやすくなるというメリットが薄いような気がしています。

2024-10-29 16:40 UTC, nomura0928 commented on backend/main.go
> +func encryptPassword(password string) (string, error) {
正直ここらへんからどうすればいいかあまりわからないです

2024-10-31 02:33 UTC, nakamuraitsuki commented on backend/main.go
> +func encryptPassword(password string) (string, error) {
createUserに合併してしまいましょう。
1. userという受け取る箱を用意。
2. decodeBodyを使って送られてきた値を翻訳してuserの中に受け取る。
3. userの中のpw_hashには、まだ暗号化されていないパスワードが入ってしまっているので、hashみたいな変数を用意して、今のencryptPassword関数と同じやり方でhashに暗号化（ハッシュ化）されたパスワードを作る。[https://zenn.dev/kou_pg_0131/articles/go-digest-and-compare-by-bcrypt](url)を参考にしてみるとよいかもしれません。
4. SQLを実行する。入れるのは名前にはuser.nameを、pw_hashにはhashを入れる
5. 成功したことを伝えるレスポンスを返す。

以上の流れです。わからない部分があったらDisicordの方でもどしどし質問ください

2024-11-02 00:54 UTC, nakamuraitsuki requested changes
pullしてエラーが出てたので、変更をお願いします。
あと、もし送られてきたChangeRequestがすべて解消できたら、コメントの下の「Resolve　Comversation」みたいなところを押す＋レビュワーのところを押してRe-Reviewをするよう通知する。という作業をお願いしたいです。そうすると、レビュワー（我々）が変更が完了したと認識して再度チェックします。

2024-11-02 00:54 UTC, nakamuraitsuki commented on backend/main.go
> +	_, err := db.Exec(addUser, user.Name, hash)
:=だとエラーが出るはずです。（:=は左に新しい変数がある場合のみ）
なので、＝にすると良いと思います
```suggestion
	_, err = db.Exec(addUser, user.Name, hash)
```

2024-11-03 02:46 UTC, nakamuraitsuki requested changes
多分これでラスト！頑張ってください

2024-11-03 02:46 UTC, nakamuraitsuki commented on backend/main.go
> +	hash, err = bcrypt.GenerateFromPassword([]byte(user.PwHash), bcrypt.DefaultCost)
ここは`hash, err := ~`でいいです．:=は定義の意味を持っているので、左側に新しい変数（今回で言うところの`hash`）がある場合は:=でOK。ターミナルで`go build`してみると、そのあたりがエラーとして表示されて便利ですよ。

2024-11-04 00:57 UTC, nakamuraitsuki approved these changes
LGTMです！お疲れ様でした！

2024-11-04 05:38 UTC, merged