スレッド検索機能
nakamuraitsuki/maximum_forum pull request #57
Opened 2024-11-12 02:40 UTC by batora9

一応動作確認おねがいします

2024-11-12 04:07 UTC, batora9 commented
@nakamuraitsuki さっきのエラーハンドリング修正した

2024-11-12 15:04 UTC, nakamuraitsuki submitted a review, later dismissed
少し使い勝手が悪い気がしますが、Reactの限界だと思うので妥協。

2024-11-12 15:38 UTC, batora9 commented
やりなおします

2024-11-14 02:36 UTC, nakamuraitsuki requested changes
「スライスすると配列が失われて～」みたいなことを言ってしまいましたが、よく見たらthreadが上書きされてるだけでした。
filterメソッド自体は悪くなくて、filterした結果を別の配列に持っておいて、それをmapで表示するようにすることでで解決できる問題でした、たぶん。
useMemoでも解決できてるけれど、導入する必要はないかもしれません。

2024-11-14 02:36 UTC, nakamuraitsuki commented on frontend/src/pages/Home.js
> +  }, [allThreads, searchKeyword]);
filteredThreadsを用意するなら、useMemo使わなくても良いかも。

2024-11-14 05:18 UTC, batora9 commented on frontend/src/pages/Home.js
> +  }, [allThreads, searchKeyword]);
useMemo使って`allThreads`からキーワードで絞りこんで`thread`(別の配列)に格納しているイメージだった。
Maximum AtCoder Leaderboard作るときも同じように実装したくてそらちさんから聞いたやり方がuseMemo使う方法だったんだよね

これしか思いつかんかった

2024-11-15 11:37 UTC, batora9 commented on frontend/src/pages/Home.js
> +  }, [allThreads, searchKeyword]);
これどうしようかｗ
動いてるから次すすむ？

2024-11-15 12:48 UTC, nakamuraitsuki commented on frontend/src/pages/Home.js
> +  }, [allThreads, searchKeyword]);
進めようか

2024-11-15 12:48 UTC, nakamuraitsuki approved these changes

2024-11-16 02:12 UTC, merged