A
nakamuraitsuki/maximum_forum pull request #58
Opened 2024-11-12 10:30 UTC by Tea-England

少しデザインを変えてみました
![スクリーンショット 2024-11-12 192842](https://github.com/user-attachments/assets/e0b402c2-8f16-4c00-924d-304f663db2f5)

2024-11-12 14:10 UTC, batora9 commented
Aってタイトルじゃ何だかわからないから直してほしい

2024-11-17 10:04 UTC, Tea-England commented
git pushまでやり直しました。

2024-11-17 13:24 UTC, batora9 commented
背景色は変更できるようにしないんだっけ？

2024-11-17 13:25 UTC, batora9 requested changes

2024-11-17 13:25 UTC, batora9 commented on frontend/src/pages/Register.css
>    border-radius: 8px;
```suggestion
  background-color: #b8ebfd;
  border-radius: 8px;
```

2024-11-17 13:25 UTC, batora9 commented on frontend/src/pages/Register.css
>    border-radius: 8px;
無駄な改行があるから消してほしい

2024-11-18 03:19 UTC, Tea-England commented on frontend/src/pages/Register.css
>    border-radius: 8px;
わかりました。やってきます。
背景に関しては四角の中は変更できましたがかえって見づらくなってしまうのでそのままにしましたよ。

2024-11-30 10:21 UTC, closed without merging