Feat/comment limit
nakamuraitsuki/maximum_forum pull request #61
Opened 2024-11-18 10:41 UTC by nakamuraitsuki

2024-11-19 17:08 UTC, batora9 commented
テスト終わってから見ます

2024-11-25 12:42 UTC, batora9 commented
スレッドページで現在のコメント数を`3/1000`みたいな感じで表示してほしい

2024-11-25 12:43 UTC, batora9 requested changes

2024-11-25 12:43 UTC, batora9 commented on frontend/src/pages/Thread.js
> +        alert("コメントの上限に達しています。");
alertはあんまり使わない方がいいかな～なんとなく

2024-11-25 12:47 UTC, nakamuraitsuki commented on frontend/src/pages/Thread.js
> +        alert("コメントの上限に達しています。");
そこの考案を誰かに頼みたい。どうするのがgood UI?
//TODO:上限を迎えていてなおコメントをポストした際の表示

2024-11-25 12:49 UTC, nakamuraitsuki commented
> スレッドページで現在のコメント数を`3/1000`みたいな感じで表示してほしい

承知しました。

2024-11-25 14:51 UTC, batora9 approved these changes

2024-11-25 14:51 UTC, batora9 commented on frontend/src/pages/Thread.js
> +        alert("コメントの上限に達しています。");
```html
<div>{isLimitReached && <p>コメント上限に達しています</p>}</div>
```
これあるからOK。alert部分だけ消してくれればいいかな

2024-11-25 14:51 UTC, merged